modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayURL = "https://space.bilibili.com/506597031"
description = '''
${mod_description}
'''

[[dependencies.inventory_stages]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventory_stages]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventory_stages]]
modId = "gamestages"
mandatory = true
versionRange = "[14,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventory_stages]]
modId = "kubejs"
mandatory = false
versionRange = "[2001.6.5,)"
ordering = "NONE"
side = "BOTH"
